name: PHP Composer

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp_server: ${{ secrets.FTP_HOST }}
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.ftp_password }}
        git-ftp-args: --remote-root ${{ secrets.FTP_REMOTE_ROOT }}
        local-dir: pages
